# Builds the project and uploads a debug APK
name: Android PR CI

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build, Sign & Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Signed app bundle
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 3
